### ISSUE TITLE
v1 should not be broken forever!

### ISSUE THREAD

**Issue by CAMOBAP** [actions-mn/build-and-publish#15]
After discussion https://github.com/metanorma/coradoc/pull/101#issuecomment-2154724487

We agreed to fix v1 to support both old an new metanorma based on version check

**Comment by CAMOBAP** [comment]
site-gen action fixed for v1 so `build-and-publish@v1` which rely on site-gen@v1 should be fixed too

cc @ronaldtse

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP !!

**Comment by ronaldtse** [comment]
@CAMOBAP does that mean we now have the ability to choose Metanorma versions to run via GHA? Like how Ruby versions work?

**Comment by CAMOBAP** [comment]
> @CAMOBAP does that mean we now have the ability to choose Metanorma versions to run via GHA? Like how Ruby versions work?

To be on the same page in GHA we have two ways to setup version of metanorma:
1. In a  container i.e.
    ```
    ...
    runs-on: ubuntu-latest
    container:
      image: metanorma/metanorma:x.y.z
    ...
    ```
2. in our `actions-mn/setup`
    ```
    ...
    steps:
      - uses: actions/checkout@v4
      - uses: actions-mn/setup@v1
         with:
           version: x.y.z
    ```

Those ones was there long time before and we use the for some our abandoned flavors already
