### ISSUE TITLE
Why did it restore cache & then still had to generate Metanorma XML?

### ISSUE THREAD

**Issue by strogonoff** [actions-mn/build-and-publish#21]
Run: https://github.com/strogonoff/cc-admin-documents/actions/runs/14587249280/job/40914898718

<img width="818" alt="Image" src="https://github.com/user-attachments/assets/3442321c-080b-41d9-adad-8d79d60b1e61" />

Workflow: https://github.com/strogonoff/cc-admin-documents/blob/248dceb202e234059274dd10f0cbcc88464ce38d/.github/workflows/docker.yml#L18

```yaml
  build:
    runs-on: ubuntu-latest
    container:
      image: metanorma/metanorma:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Bundler install
        uses: metanorma/ci/docker-gem-install@main

      - name: Print Metanorma version
        run: metanorma --version

      - name: Generate Metanorma XML
        uses: actions-mn/build-and-publish@v2
        with:
          destination: artifact
          artifact-name: mn
          agree-to-terms: true
```
