### ISSUE TITLE
Provide full examples in README on how to use with private repos/flavors

### ISSUE THREAD

**Issue by ronaldtse** [actions-mn/build-and-publish#3]
Provide full examples in README on how to use with private repos/flavors:

1. Using Metanorma in private repository (e.g. https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2)
2. Using a private metanorma flavor (e.g. bsi/nist)

Thanks!

_Originally posted by @ronaldtse in https://github.com/actions-mn/build-and-publish/issues/1#issuecomment-1319499716_

**Comment by CAMOBAP** [comment]
@ronaldtse 

1. There is no difference between using metanorma in private or public repo
2. Added complete example with `setup-flavors` in README https://github.com/actions-mn/build-and-publish/blob/main/README.md

**Comment by ronaldtse** [comment]
@CAMOBAP Thanks! However there seems to be an inconsistency in the Docker vs Ubuntu YAMLs:

Docker:
```yaml
      - name: Metanorma generate site
        uses: actions-mn/build-and-publish@main
        with:
          agree-to-terms: true
          output-dir: ./_site
```

Ubuntu:
```yaml
      - name: Metanorma generate site
        uses: actions-mn/build-and-publish@main
        with:
          agree-to-terms: true
```

Which one is correct?
