### ISSUE TITLE
Making PR artifacts available via GitHub Pages?

### ISSUE THREAD

**Issue by ronaldtse** [actions-mn/build-and-publish#4]
From @hasel001 of @iho-ohi :

> Right now, to get to the Word document, I have been using the process below:
> 
> a. Go to the Pull request in question
> b. Go to Checks
> c. If it exists, download the zip file from Artifacts
> c2. If it has expired, re-run the processes to regenerate the artifacts.
> d. Unzip/expand to get to the file.
> 
> Is there a process that can more easily make the documents available (especially to more novice GitHub users)?

It looks possible to deploy PR builds to a GitHub Pages site:
* https://github.com/marketplace/actions/deploy-pr-preview
 
However we will need to deal with retentions (i.e. once the PR is merged, we want to delete those files?).

Can we integrate it with some action-mn we have?

**Comment by CAMOBAP** [comment]
I think this can be easily extended to support `deployment-pr-preview` by adding one more step at the bottom build job

```yml
name: generate

on:
  workflow_call:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: metanorma/metanorma:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Metanorma assets
        uses: actions-mn/cache@v1

      - name: Metanorma generate site
        uses: actions-mn/build-and-publish@v1
        with:
          agree-to-terms: true

      - name: Deploy preview
        if: ${{ github.event_name== 'pull_request' }}
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```

@ronaldtse I think it's hard to implement this at the actions level but we can update our reusable workflow  https://github.com/metanorma/ci/blob/main/.github/workflows/user-docker.yml

Also to prevent overriding PR preview we may need to move out of `actions/deploy-pages@v1` to `JamesIves/github-pages-deploy-action@v4`

@ronaldtse maybe you can suggest some repository to try it out? Also should we implement this for our mn-samples-* repos too?
